version: "3.8"

services:
  server:
    build: ./server
    ports:
      - "8787:8787"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./server:/app
      - chroma_data:/app/.chroma
    command: uvicorn app.app:app --host 0.0.0.0 --port 8787 --reload
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8787/status?repo=test&prNumber=1&commit=main",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  chroma_data:
